"""Repository port for the guided-session store."""

from __future__ import annotations

from typing import Protocol


class SessionRepository(Protocol):
    def create(self, session_id: str, data: dict) -> dict: ...
    def get(self, session_id: str) -> dict | None: ...
    def update(self, session_id: str, data: dict) -> dict: ...
    def all(self) -> dict: ...
