"""Repository port for the identity service (hexagonal)."""

from __future__ import annotations

from typing import Protocol


class IdentityRepository(Protocol):
    # users
    def create_user(self, tenant_id: str, email: str, pw_salt: str,
                    pw_hash: str, role: str, name: str) -> dict: ...
    def get_user(self, user_id: str) -> dict | None: ...
    def get_by_email_raw(self, tenant_id: str, email: str) -> dict | None: ...
    def find_by_email_raw(self, email: str) -> list[dict]: ...
    def get_user_raw(self, user_id: str) -> dict | None: ...
    def set_mfa(self, user_id: str, secret: str, enabled: bool) -> None: ...
    def list_users(self, tenant_id: str) -> list[dict]: ...
    # CAMP-SSO-OIDC: bind/lookup a user against a verified IdP subject
    def get_user_by_idp(self, tenant_id: str, issuer: str,
                        subject: str) -> dict | None: ...
    def bind_idp(self, user_id: str, issuer: str, subject: str) -> None: ...

    # sessions
    def create_session(self, token: str, user: dict, expires_at: str,
                       scope: str = "full",
                       identity: dict | None = None) -> None: ...
    def get_session(self, token: str) -> dict | None: ...
    # sliding renewal: move a live session's expiry forward (no-op if gone)
    def touch_session(self, token: str, expires_at: str) -> None: ...
    def delete_session(self, token: str) -> None: ...
    def delete_sessions_for_tenant(self, tenant_id: str) -> None: ...
    def delete_sessions_for_tenant_without_mfa(self, tenant_id: str) -> None: ...

    # tenants
    def create_tenant(self, tenant_id: str, name: str, plan_id: str,
                      status: str) -> dict: ...
    def get_tenant(self, tenant_id: str) -> dict | None: ...
    def list_tenants(self) -> list[dict]: ...
    def set_tenant_plan(self, tenant_id: str, plan_id: str) -> dict | None: ...
    def set_tenant_status(self, tenant_id: str, status: str) -> dict | None: ...
    def set_billing(self, tenant_id: str, billing_status: str,
                    grace_until) -> dict | None: ...
    def set_require_mfa(self, tenant_id: str,
                        require_mfa: bool) -> dict | None: ...

    # plans + overrides
    def create_plan(self, plan_id: str, name: str, features: list) -> dict: ...
    def get_plan(self, plan_id: str) -> dict | None: ...
    def list_plans(self) -> list[dict]: ...
    def set_override(self, tenant_id: str, feature: str, enabled: bool) -> None: ...
    def list_overrides(self, tenant_id: str) -> dict: ...

    # CAMP-SSO-OIDC: per-workspace SSO config + in-flight OIDC login state
    def set_sso_config(self, tenant_id: str, enabled: bool, issuer: str,
                       client_id: str, client_secret: str,
                       redirect_uri: str) -> dict: ...
    def get_sso_config(self, tenant_id: str) -> dict | None: ...
    def create_sso_flow(self, state: str, tenant_id: str, nonce: str,
                        code_verifier: str, redirect_uri: str,
                        expires_at: str) -> None: ...
    def get_sso_flow(self, state: str) -> dict | None: ...
    def delete_sso_flow(self, state: str) -> None: ...
