"""Repository port for the lifecycle service."""

from __future__ import annotations

from typing import Protocol


class LifecycleRepository(Protocol):
    def save(self, state: dict, tenant_id: str | None = None) -> dict: ...
    def get(self, dossier_id: str) -> dict | None: ...
    def get_tenant(self, dossier_id: str) -> str | None: ...
    def list(self) -> list[dict]: ...
    def add_correspondence(self, record: dict,
                           tenant_id: str | None = None) -> dict: ...
    def list_correspondence(self, dossier_id: str, kind: str = "",
                            tenant_id: str | None = None) -> list[dict]: ...
    def add_noa(self, record: dict,
                tenant_id: str | None = None) -> dict: ...
    def get_noa(self, noa_id: str) -> dict | None: ...
    def get_noa_tenant(self, noa_id: str) -> str | None: ...
    def save_noa(self, record: dict) -> dict: ...
    def list_noa(self, dossier_id: str,
                 tenant_id: str | None = None) -> list[dict]: ...
    def add_shortage(self, record: dict,
                     tenant_id: str | None = None) -> dict: ...
    def list_shortage(self, dossier_id: str,
                      tenant_id: str | None = None) -> list[dict]: ...
    def add_del_link(self, record: dict,
                     tenant_id: str | None = None) -> dict: ...
    def list_del_links(self, dossier_id: str,
                       tenant_id: str | None = None) -> list[dict]: ...
