"""Repository port for the lifecycle service."""

from __future__ import annotations

from typing import Protocol


class LifecycleRepository(Protocol):
    def save(self, state: dict) -> dict: ...
    def get(self, dossier_id: str) -> dict | None: ...
    def list(self) -> list[dict]: ...
    def add_correspondence(self, record: dict) -> dict: ...
    def list_correspondence(self, dossier_id: str,
                            kind: str = "") -> list[dict]: ...
    def add_noa(self, record: dict) -> dict: ...
    def get_noa(self, noa_id: str) -> dict | None: ...
    def save_noa(self, record: dict) -> dict: ...
    def list_noa(self, dossier_id: str) -> list[dict]: ...
    def add_shortage(self, record: dict) -> dict: ...
    def list_shortage(self, dossier_id: str) -> list[dict]: ...
    def add_del_link(self, record: dict) -> dict: ...
    def list_del_links(self, dossier_id: str) -> list[dict]: ...
