"""FORMS-ENGINE: every eCTD content section is form-fillable + AI-draftable +
generatable — not just upload. Proves the form-schema contract, the universal
``structured`` generator, the section-tree wiring, and per-field AI draft.
"""

from app import drafting, form_schemas, generators, pdfgen, section_tree

# The field types allowed by the SHARED FORM-SCHEMA CONTRACT.
_TYPES = {"text", "textarea", "date", "select", "email", "number"}


# --- (2) a declarative schema for EVERY authorable document section ---------

def _document_sections() -> list[str]:
    """Every content (document) section in the tree that is authorable, i.e.
    exposes a generator_key. Group nodes and the auto-backbone are excluded."""
    return [n["section"] for n in section_tree.all_nodes()
            if n["kind"] == "document" and n.get("generator_key")]


def test_every_authorable_document_section_has_a_form_schema():
    missing = [s for s in _document_sections()
               if form_schemas.form_schema(s) is None]
    assert not missing, f"sections with a generator but no form schema: {missing}"


def test_schema_conforms_to_the_shared_contract():
    for section, schema in form_schemas.registry().items():
        assert set(schema) >= {"section", "title", "description",
                               "generator", "fields"}, section
        assert schema["section"] == section
        assert schema["title"] and schema["description"]
        assert schema["generator"]
        assert schema["fields"], f"{section} has no fields"
        for f in schema["fields"]:
            assert set(f) >= {"name", "label", "type", "required", "prose",
                              "help"}, f"{section}.{f.get('name')}"
            assert f["type"] in _TYPES, f"{section}.{f['name']} bad type {f['type']}"
            assert isinstance(f["required"], bool)
            assert isinstance(f["prose"], bool)
            assert f["help"], f"{section}.{f['name']} missing HC help one-liner"
            if f["type"] == "select":
                assert f.get("options"), f"{section}.{f['name']} select needs options"


def test_group_and_backbone_sections_have_no_schema():
    # group nodes (1.2, 1.3, 3.2.S, 3.2.P) and the auto-backbone (1.1, 2.1)
    for s in ("1.1", "1.2", "1.3", "2.1", "3.2.S", "3.2.P"):
        assert form_schemas.form_schema(s) is None, s


def test_existing_generator_sections_registered_with_bespoke_generator():
    # the six special-format documents keep their bespoke generator key
    for section, key in form_schemas.BESPOKE_GENERATORS.items():
        assert form_schemas.form_schema(section)["generator"] == key


def test_prose_fields_are_flagged_for_ai_draft():
    # a representative structured section exposes at least one prose field
    assert "content" in form_schemas.prose_fields("3.2.P.1")
    assert form_schemas.field_for("3.2.P.1", "content")["prose"] is True


# --- (3) the universal "structured" generator renders a PDF/A-clean doc -----

def _pdfa_clean(body: bytes) -> bool:
    return (body.startswith(b"%PDF-")
            and b"pdfaid:part=\"1\"" in body
            and b"GTS_PDFA1" in body
            and body.rstrip().endswith(b"%%EOF"))


def test_structured_generator_renders_valid_pdfa_from_filled_schema():
    schema = form_schemas.form_schema("3.2.P.1")
    form = {"drug_product": "Drugazole 10 mg tablet",
            "content": "The finished tablet matches the reference product."}
    doc = generators.structured_document(schema, form)
    assert doc["content_type"] == "application/pdf"
    assert doc["filename"].endswith(".pdf")
    assert _pdfa_clean(doc["body"])
    # the field value is rendered into the document text
    text = pdfgen._latin1  # sanity: module import
    assert doc["title"] == schema["title"]


def test_structured_generator_marks_required_placeholder_when_empty():
    schema = form_schemas.form_schema("2.2")   # drug_product is required
    doc = generators.structured_document(schema, {})
    # required-but-empty renders an explicit placeholder, never silent blank
    assert b"PLACEHOLDER" in doc["body"]


def test_structured_generator_carries_draft_watermark():
    schema = form_schemas.form_schema("2.2")
    doc = generators.structured_document(schema, {"drug_product": "X"})
    assert b"DRAFT generated by ANDS Studio" in doc["body"]


# --- (4) the eCTD tree exposes "generate" on every content section ----------

# The only content sections that remain WITHOUT an in-app generate affordance,
# each for a principled reason:
#   1.1 / 2.1 — the eCTD auto-backbone (index.xml / ca-regional.xml), no document
#   1.2.2     — fees/small-business: you UPLOAD HC's fee form / payment proof;
#               there is no honest prose document to author here
#   1.3.1     — the XML Product Monograph is built in workstream 2 (pm_xml),
#               which owns its own generate wiring
_UPLOAD_ONLY_BY_DESIGN = {"1.1", "2.1", "1.2.2", "1.3.1"}


def test_every_content_section_exposes_generate():
    offenders = []
    for n in section_tree.all_nodes():
        if n["kind"] != "document":
            continue
        if n["section"] in _UPLOAD_ONLY_BY_DESIGN:
            continue
        if "generate" not in n["affordances"] or not n.get("generator_key"):
            offenders.append(n["section"])
    assert not offenders, f"content sections still upload-only: {offenders}"


def test_fees_section_stays_upload_only_by_design():
    # 1.2.2 is a payment/fee form — upload HC's form, do not "author" it
    n = section_tree.node_for("1.2.2")
    assert "generate" not in n["affordances"]
    assert n["affordances"] == ["upload"]


def test_product_monograph_1_3_1_left_for_workstream2():
    # 1.3.1's real (pm_xml) generator is workstream 2; the tree node is not
    # rewired here, but a stub form schema exists so the form UI is uniform.
    assert section_tree.node_for("1.3.1")["generator_key"] is None
    assert form_schemas.form_schema("1.3.1")["generator"] == "pm_xml"


def test_previously_upload_only_sections_now_generate_structured():
    for s in ("1.2.5", "1.3.3", "2.2", "3.2.S.1", "3.2.P.8", "3.3", "5.3.1"):
        n = section_tree.node_for(s)
        assert "generate" in n["affordances"], s
        assert n["generator_key"] == "structured", s
        assert "upload" in n["affordances"], s   # upload preserved


def test_generate_and_mark_na_preserved_where_they_existed():
    n = section_tree.node_for("3.2.S.5")   # was [upload, mark_na]
    assert set(n["affordances"]) >= {"generate", "upload", "mark_na"}


def test_backbone_and_groups_unchanged():
    assert section_tree.node_for("1.1")["affordances"] == []
    assert section_tree.node_for("2.1")["affordances"] == []
    assert section_tree.node_for("1.2")["kind"] == "group"


# --- (5) generate("structured", ctx-with-form) works end to end -------------

def test_generate_structured_via_registry_uses_section_schema_and_form():
    ctx = {"section": "3.2.S.7",
           "form": {"drug_product": "Drugazole 10 mg tablet",
                    "content": "12 months accelerated, 24 months long-term."}}
    doc = generators.generate("structured", ctx)
    assert _pdfa_clean(doc["body"])
    assert doc["title"] == form_schemas.form_schema("3.2.S.7")["title"]


def test_generate_structured_without_form_key_falls_back_to_ctx():
    ctx = {"section": "2.2", "drug_product": "Drugazole 10 mg tablet"}
    doc = generators.generate("structured", ctx)
    assert _pdfa_clean(doc["body"])


def test_generate_structured_unknown_section_raises_keyerror():
    import pytest
    with pytest.raises(KeyError):
        generators.generate("structured", {"section": "9.9.9"})


def test_structured_registered_in_generate_dispatch():
    # bespoke generators still resolve; "structured" is a first-class key
    doc = generators.generate("cover_letter", {"sponsor": "Acme Pharma Inc."})
    assert doc["content_type"] == "application/pdf"


# --- (6) draft_field returns a focused per-field system prompt --------------

def test_draft_field_returns_focused_prompt_for_a_prose_field():
    ctx = {"drug_product": "Drugazole 10 mg tablet", "dossier_id": "D-123"}
    prompt = drafting.draft_field("3.2.P.1", "content", ctx)
    assert isinstance(prompt, str) and prompt
    # grounded in the field + section + honesty guardrail
    assert "3.2.P.1" in prompt
    assert "PLACEHOLDER" in prompt          # honesty: no fabrication
    assert "Drugazole 10 mg tablet" in prompt   # known facts injected
    assert "only the text for this one field" in prompt.lower()


def test_draft_field_flags_bilingual_fields():
    prompt = drafting.draft_field("1.3.3", "inner_label", {})
    assert "BILINGUAL" in prompt


def test_draft_field_rejects_non_prose_or_unknown_field():
    import pytest
    with pytest.raises(KeyError):
        drafting.draft_field("2.2", "drug_product", {})   # not prose
    with pytest.raises(KeyError):
        drafting.draft_field("2.2", "nonexistent", {})
