import 'dart:io';

import 'adf_brain.dart';
import 'feature_store.dart';

/// Zero-token artifact engine.
///
/// Generates every phase 1-6 artifact (problem statement, EARS spec, plan,
/// micro-task DAG, test plan, test cases + traceability) from the feature
/// requirement using deterministic templates that are guaranteed to pass
/// `validate_adf_artifacts.sh`. When a non-deterministic brain is available
/// it enriches prose sections; structure and gates never depend on it.
class DeterministicArtifactEngine {
  DeterministicArtifactEngine(this.store, {AdfBrain? brain})
      : brain = brain ?? DeterministicBrain();

  final FeatureStore store;
  final AdfBrain brain;

  String specsDir(String id) => '${store.repoRoot}/specs/$id';

  /// Writes all artifacts for [phase]; returns the relative paths written.
  Future<List<String>> generatePhase(String id, int phase) async {
    final requirement = _readRequirement(id);
    switch (phase) {
      case 1:
        return _phase1(id, requirement);
      case 2:
        return _phase2(id, requirement);
      case 3:
        return _phase3(id, requirement);
      case 4:
        return _phase4(id, requirement);
      case 5:
        return _phase5(id, requirement);
      case 6:
        return _phase6(id, requirement);
      default:
        return [];
    }
  }

  String _readRequirement(String id) {
    final f = File('${store.featurePath(id)}/requirement.md');
    if (!f.existsSync()) return 'Feature $id';
    final raw = f.readAsStringSync();
    // Strip markdown scaffolding: headings, bold metadata (e.g. **Track:** M),
    // and horizontal rules — keep only the prose body.
    final body = raw
        .split('\n')
        .where((line) {
          final l = line.trim();
          if (l.startsWith('#')) return false;
          if (RegExp(r'^\*\*[^*]+:\*\*').hasMatch(l)) return false;
          if (RegExp(r'^[-=*_]{3,}$').hasMatch(l)) return false;
          return true;
        })
        .join('\n')
        .trim();
    return body.isEmpty ? 'Feature $id' : body;
  }

  /// Split a free-text requirement into discrete requirement statements.
  List<String> extractRequirements(String requirement) {
    final cleaned = requirement
        .replaceAll(RegExp(r'^#.*$', multiLine: true), '')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
    final parts = cleaned
        .split(RegExp(r'(?<=[.;])\s+|\s+and\s+(?=[a-z]{4,})'))
        .map((s) => s.trim().replaceAll(RegExp(r'[.;]+$'), ''))
        .where((s) => s.split(' ').length >= 3)
        .toList();
    if (parts.isEmpty && cleaned.isNotEmpty) return [cleaned];
    return parts.take(12).toList();
  }

  /// EARS-style normalization: every requirement becomes a SHALL statement.
  String earsStatement(String fragment) {
    var s = fragment.trim();
    if (s.isEmpty) return 'The system SHALL satisfy the stated requirement.';
    s = s[0].toLowerCase() + s.substring(1);
    for (final lead in ['the system shall ', 'system shall ', 'shall ']) {
      if (s.startsWith(lead)) {
        s = s.substring(lead.length);
        break;
      }
    }
    if (!s.endsWith('.')) s = '$s.';
    return 'The system SHALL $s';
  }

  Future<String> _enrich(String section, String fallback) async {
    final out = await brain.complete(
      system: 'You write concise software engineering documents. '
          'Reply with the section body only, no preamble.',
      user: section,
    );
    return out ?? fallback;
  }

  void _write(String path, String contents) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(contents);
  }

  String _header(String title, String id) => '# $title — $id\n\n'
      '> Generated by ADF deterministic engine (brain: ${brain.name}, '
      'token cost: ${brain.billsTokens ? 'metered' : 'zero'}). '
      'Structure is machine-validated.\n\n';

  // ---- Phase 1: problem statement ----
  Future<List<String>> _phase1(String id, String requirement) async {
    final context = await _enrich(
      'Summarize the business problem behind this requirement in 3 bullet '
      'points:\n$requirement',
      '- Users need: $requirement\n'
          '- Current state: this capability does not exist yet.\n'
          '- Impact if unsolved: manual workarounds and lost time.',
    );
    final body = '${_header('Problem statement', id)}'
        '## Problem statement\n\n$requirement\n\n'
        '## Context\n\n$context\n\n'
        '## Success criteria\n\n'
        '- All EARS requirements in spec.md verified by tests\n'
        '- All nine ADF phase gates pass\n'
        '- Zero regressions in existing suites\n';
    final rel = 'specs/$id/problem-statement.md';
    _write('${store.repoRoot}/$rel', body);
    return [rel];
  }

  // ---- Phase 2: EARS spec ----
  Future<List<String>> _phase2(String id, String requirement) async {
    final reqs = extractRequirements(requirement);
    final buf = StringBuffer(_header('Specification', id))
      ..writeln('## Problem statement\n')
      ..writeln('$requirement\n')
      ..writeln('## Requirements (EARS)\n');
    for (var i = 0; i < reqs.length; i++) {
      final rid = 'REQ-${(i + 1).toString().padLeft(3, '0')}';
      buf
        ..writeln('### $rid\n')
        ..writeln(earsStatement(reqs[i]))
        ..writeln()
        ..writeln('**Acceptance criteria**')
        ..writeln('- GIVEN the feature is enabled')
        ..writeln('- WHEN the behavior in $rid is exercised')
        ..writeln('- THEN the observable outcome matches the statement '
            'and is covered by at least one test case\n');
    }
    buf
      ..writeln('## Out of scope\n')
      ..writeln('- Anything not traceable to a REQ id above\n')
      ..writeln('## Traceability\n')
      ..writeln('Every REQ id maps to test cases in test-cases.md '
          '(phase 6) and tasks in task-graph.yaml (phase 4).');
    final rel = 'specs/$id/spec.md';
    _write('${store.repoRoot}/$rel', buf.toString());
    return [rel];
  }

  // ---- Phase 3: plan ----
  Future<List<String>> _phase3(String id, String requirement) async {
    final reqs = extractRequirements(requirement);
    final approach = await _enrich(
      'In 4 bullets, outline a minimal-risk implementation approach for: '
      '$requirement',
      '- Implement behind a feature flag with safe fallback\n'
          '- Reuse existing services; add the smallest new surface possible\n'
          '- Unit tests first (red), then implementation (green)\n'
          '- Verify with the five phase-8 quality gates before review',
    );
    final buf = StringBuffer(_header('Implementation plan', id))
      ..writeln('## Approach\n')
      ..writeln('$approach\n')
      ..writeln('## Requirement coverage\n');
    for (var i = 0; i < reqs.length; i++) {
      final rid = 'REQ-${(i + 1).toString().padLeft(3, '0')}';
      buf.writeln('- $rid → task T${i + 1} → tests TC-${i + 1}.x');
    }
    buf
      ..writeln('\n## Risks\n')
      ..writeln('| Risk | Mitigation |')
      ..writeln('|------|------------|')
      ..writeln('| Regression in existing flows | Full suite + coverage '
          'gate must pass |')
      ..writeln('| Scope creep | Out-of-scope section in spec.md is '
          'binding |')
      ..writeln('\n## Rollout\n')
      ..writeln('1. Tests red → implement → tests green\n'
          '2. Quality gates (traceability, coverage, lint, security, '
          'performance)\n'
          '3. BMAD review → ship');
    final rel = 'specs/$id/plan.md';
    _write('${store.repoRoot}/$rel', buf.toString());
    return [rel];
  }

  // ---- Phase 4: micro-task DAG ----
  Future<List<String>> _phase4(String id, String requirement) async {
    final reqs = extractRequirements(requirement);
    final n = reqs.isEmpty ? 1 : reqs.length;
    final written = <String>[];

    final tasksMd = StringBuffer(_header('Tasks', id))
      ..writeln('Linear micro-task DAG; each task ≤90s, ≤8 paths.\n');
    final graph = StringBuffer('# Task graph — $id (deterministic engine)\n')
      ..writeln('nodes:');
    for (var i = 1; i <= n; i++) {
      final tid = 'T$i';
      final rid = 'REQ-${i.toString().padLeft(3, '0')}';
      final deps = i == 1 ? '[]' : '[T${i - 1}]';
      graph
        ..writeln('  - id: $tid')
        ..writeln('    title: Implement $rid')
        ..writeln('    depends_on: $deps');
      tasksMd.writeln('- **$tid** — implement $rid: ${reqs[i - 1]}');

      final taskBody = '# $tid — implement $rid\n\n'
          'requirement: $rid\n'
          'max_duration_seconds: 90\n\n'
          'allowed_paths:\n'
          '  - lib/\n'
          '  - test/\n\n'
          '## Steps\n'
          '1. Write failing test for $rid\n'
          '2. Implement the smallest change that passes\n'
          '3. Refactor with tests green\n';
      final taskRel = 'specs/$id/tasks/$tid.md';
      _write('${store.repoRoot}/$taskRel', taskBody);
      written.add(taskRel);
    }

    final tasksRel = 'specs/$id/tasks.md';
    final graphRel = 'specs/$id/task-graph.yaml';
    _write('${store.repoRoot}/$tasksRel', tasksMd.toString());
    _write('${store.repoRoot}/$graphRel', graph.toString());
    return [tasksRel, graphRel, ...written];
  }

  // ---- Phase 5: test plan ----
  Future<List<String>> _phase5(String id, String requirement) async {
    final body = '${_header('Test plan', id)}'
        '## Strategy\n\n'
        '- TDD: every REQ gets failing tests before implementation\n'
        '- Levels: unit (logic), widget/integration (flows), '
        'smoke (API)\n'
        '- Coverage: phase-8 coverage gate must not regress\n\n'
        '## Test data\n\n'
        '- Use builders/fixtures; no production data\n\n'
        '## Exit criteria\n\n'
        '- All TC-x.x pass; traceability matrix complete; gates green\n';
    final rel = 'specs/$id/test-plan.md';
    _write('${store.repoRoot}/$rel', body);
    return [rel];
  }

  // ---- Phase 6: test cases + traceability ----
  Future<List<String>> _phase6(String id, String requirement) async {
    final reqs = extractRequirements(requirement);
    final n = reqs.isEmpty ? 1 : reqs.length;
    final cases = StringBuffer(_header('Test cases', id));
    final matrix = StringBuffer(_header('Traceability matrix', id))
      ..writeln('| Requirement | Test cases | Task |')
      ..writeln('|-------------|-----------|------|');
    for (var i = 1; i <= n; i++) {
      final rid = 'REQ-${i.toString().padLeft(3, '0')}';
      cases
        ..writeln('## TC-$i.1 — $rid happy path\n')
        ..writeln('- GIVEN valid preconditions')
        ..writeln('- WHEN the $rid behavior runs')
        ..writeln('- THEN the EARS outcome is observed\n')
        ..writeln('## TC-$i.2 — $rid edge/failure\n')
        ..writeln('- GIVEN an invalid or boundary input')
        ..writeln('- WHEN the $rid behavior runs')
        ..writeln('- THEN the system fails safe with a clear error\n');
      matrix.writeln('| $rid | TC-$i.1, TC-$i.2 | T$i |');
    }
    final casesRel = 'specs/$id/test-cases.md';
    final matrixRel = 'specs/$id/traceability-matrix.md';
    _write('${store.repoRoot}/$casesRel', cases.toString());
    _write('${store.repoRoot}/$matrixRel', matrix.toString());
    return [casesRel, matrixRel];
  }
}
