"""Repository port for the webhooks service."""

from __future__ import annotations

from typing import Protocol


class WebhookRepository(Protocol):
    def add_subscription(self, sub: dict) -> dict: ...
    def get_subscription(self, sub_id: str) -> dict | None: ...
    def list_subscriptions(self, *, tenant_id: str = "") -> list[dict]: ...
    def all_subscriptions(self) -> list[dict]: ...
    def delete_subscription(self, sub_id: str) -> bool: ...
    def enqueue_delivery(self, delivery: dict) -> dict: ...
    def list_deliveries(self, *, subscription_id: str = "") -> list[dict]: ...
