"use client";
// journey · J11 always-open glossary panel (round-9 MAJOR, n=6; cro_pm,
// quality_director_newcomer, startup_founder): "give me a plainer glossary I
// can open anywhere, not just hover tooltips". A slide-over panel listing
// EVERY plain-language term from lib/terms.ts (read-only import — the same
// source the dashed-underline <Term> hovers use, so definitions can't drift),
// searchable, with a per-term issuer badge: does Health Canada issue this to
// you, or does ANDS Studio generate it?
//
// HONEST SUBSET (stated in-UI below): the launcher is mounted on the guided
// journey screens; other pages keep the dashed-underline hovers + Help. An
// app-wide mount lives in TopNav, which this workstream does not own.
import { useMemo, useState } from "react";
import { BookOpen, X } from "lucide-react";
import { TERMS } from "@/lib/terms";

// Issuer marking maintained locally (additive — lib/terms.ts is not edited).
// "hc" = Health Canada issues this to you; "studio" = ANDS Studio generates
// it; unmarked keys are regulatory concepts that neither party "issues".
const HC_ISSUED = new Set([
  "Company ID", "Dossier ID", "Core ID", "DIN", "NOC", "NOD", "NON", "SDN",
  "SAL", "SRL", "clarifax",
]);
const STUDIO_GENERATED = new Set([
  "backbone", "md5 fingerprint", "md5", "provenance chip", "module badge",
  "applicability badge", "eCTD placement",
]);

function badge(k: string): { label: string; cls: string } | null {
  if (HC_ISSUED.has(k))
    return { label: "Health Canada issues this to you", cls: "ready" };
  if (STUDIO_GENERATED.has(k))
    return { label: "Generated by ANDS Studio", cls: "" };
  return null;
}

export function GlossaryPanel() {
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState("");

  const entries = useMemo(() => {
    const all = Object.entries(TERMS).sort(([a], [b]) =>
      a.toLowerCase().localeCompare(b.toLowerCase()));
    const needle = q.trim().toLowerCase();
    if (!needle) return all;
    return all.filter(
      ([k, v]) =>
        k.toLowerCase().includes(needle) || v.toLowerCase().includes(needle)
    );
  }, [q]);

  return (
    <>
      {/* the always-available launcher on the journey screens */}
      <button
        className="ghost"
        style={{
          position: "fixed",
          right: 18,
          bottom: 18,
          zIndex: 60,
          display: "inline-flex",
          alignItems: "center",
          gap: 6,
          fontSize: 12,
          padding: "7px 12px",
          borderRadius: 999,
          boxShadow: "0 2px 10px rgba(0,0,0,.12)",
          background: "var(--card, #fff)",
        }}
        aria-expanded={open}
        onClick={() => setOpen((o) => !o)}
        title="Open the plain-language glossary — every regulatory term, searchable"
      >
        <BookOpen size={13} aria-hidden /> Glossary
      </button>

      {open && (
        <aside
          role="dialog"
          aria-label="Plain-language glossary"
          className="card glass"
          style={{
            position: "fixed",
            top: 0,
            right: 0,
            bottom: 0,
            width: "min(430px, 92vw)",
            zIndex: 70,
            overflowY: "auto",
            padding: 18,
            borderRadius: 0,
            boxShadow: "-6px 0 24px rgba(0,0,0,.18)",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <h2 style={{ margin: 0, fontSize: 16 }}>Plain-language glossary</h2>
            <button
              className="ghost"
              style={{ marginLeft: "auto", padding: "3px 8px" }}
              onClick={() => setOpen(false)}
              aria-label="Close the glossary"
            >
              <X size={14} aria-hidden />
            </button>
          </div>
          <p className="mut" style={{ fontSize: 12, margin: "8px 0 10px" }}>
            Every term the app explains on hover, in one openable place. Badges
            say whether <b>Health Canada issues</b> the item to you or{" "}
            <b>ANDS Studio generates</b> it; unmarked entries are regulatory
            concepts. Open here on the journey screens — other pages keep the
            dashed-underline hovers and the Help page.
          </p>
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder={`Search ${Object.keys(TERMS).length} terms…`}
            aria-label="Search the glossary"
          />
          <dl style={{ margin: "12px 0 0" }}>
            {entries.map(([k, v]) => {
              const b = badge(k);
              return (
                <div
                  key={k}
                  style={{
                    padding: "9px 0",
                    borderTop: "1px solid var(--line)",
                  }}
                >
                  <dt
                    style={{
                      fontWeight: 700,
                      fontSize: 13,
                      display: "flex",
                      gap: 8,
                      alignItems: "center",
                      flexWrap: "wrap",
                    }}
                  >
                    {k}
                    {b && (
                      <span className={`chip ${b.cls}`} style={{ fontSize: 10 }}>
                        {b.label}
                      </span>
                    )}
                  </dt>
                  <dd
                    className="mut"
                    style={{ margin: "4px 0 0", fontSize: 12.5, lineHeight: 1.5 }}
                  >
                    {v}
                  </dd>
                </div>
              );
            })}
            {entries.length === 0 && (
              <div className="mut" style={{ fontSize: 13, marginTop: 12 }}>
                No term matches “{q}”.
              </div>
            )}
          </dl>
        </aside>
      )}
    </>
  );
}
