"""Repository port for the registry service."""

from __future__ import annotations

from typing import Protocol


class RegistrationRepository(Protocol):
    def add(self, registration: dict) -> dict: ...
    def get(self, reg_id: str) -> dict | None: ...
    def list(self, *, product: str = "", country: str = "", din: str = "",
             status: str = "", dossier_id: str = "",
             tenant_id: str = "") -> list[dict]: ...
    def set_status(self, reg_id: str, status: str) -> dict | None: ...
    def get_checklist(self, tenant_id: str, year: int) -> list[dict]: ...
    def set_checklist_item(self, tenant_id: str, year: int, item_key: str,
                           done: bool, signed_by: str | None,
                           signed_at: str | None) -> dict: ...
