"""In-app document authoring — portal-generated eCTD documents (pure).

For the sections Health Canada lets the sponsor author from their own data, the
portal produces a structured draft document (grounded in HC's templates) so the
filer doesn't start from a blank page. Each generator takes a context dict
(dossier identifiers + product + any form fields) and returns bytes + filename +
content-type; the service stores those bytes through the SAME document store and
files the SAME eCTD leaf as an upload (``origin="generated"``). Drafts are clearly
marked so the sponsor reviews/finalises before signing/filing.

Keyed by the section tree's ``generator_key``.
"""

from __future__ import annotations

_ACTIVITY_LABELS = {
    "ANDS": "Abbreviated New Drug Submission (ANDS)",
    "NDS": "New Drug Submission (NDS)",
    "SANDS": "Supplement to an ANDS (SANDS)",
    "SNDS": "Supplement to an NDS (SNDS)",
    "DIN": "Drug Identification Number Application (DINA)",
}


def _s(v) -> str:
    return str(v if v is not None else "").strip()


def _g(ctx: dict, *keys, default="—") -> str:
    for k in keys:
        v = _s((ctx or {}).get(k))
        if v:
            return v
    return default


def _doc(title: str, body: str, filename: str) -> dict:
    header = (f"{title}\n" + "=" * len(title) +
              "\n\n[DRAFT generated by ANDS Studio — review and finalise before "
              "signing/filing.]\n\n")
    return {"title": title, "filename": filename,
            "content_type": "text/plain; charset=utf-8",
            "body": (header + body).encode("utf-8")}


def cover_letter(ctx: dict) -> dict:
    body = (
        f"Sponsor:        {_g(ctx, 'applicant', 'company', 'title')}\n"
        f"Company ID:     {_g(ctx, 'company_id')}\n"
        f"Dossier ID:     {_g(ctx, 'dossier_id')}\n"
        f"Drug product:   {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"Activity type:  {_ACTIVITY_LABELS.get(_g(ctx, 'activity_type', 'submission_type', default='ANDS').upper(), 'Abbreviated New Drug Submission (ANDS)')}\n"
        f"Sequence:       {_g(ctx, 'sequence', default='0000')}\n\n"
        "This cover letter accompanies the regulatory transaction identified "
        "above, submitted to Health Canada in eCTD format. The enclosed "
        "documents are organised per the Organization and document placement for "
        "Canadian Module 1 table.\n\n"
        "Regulatory contact: " + _g(ctx, 'contact', 'contact_email') + "\n")
    return _doc("Health Canada — Cover Letter", body, "cover-letter.txt")


def rep_application_form(ctx: dict) -> dict:
    body = (
        "Regulatory Enrolment Process (REP) — application summary\n\n"
        "-- Company (CO) --\n"
        f"  Company name:  {_g(ctx, 'applicant', 'company', 'title')}\n"
        f"  Company ID:    {_g(ctx, 'company_id')}\n\n"
        "-- Regulatory Transaction (RT) --\n"
        f"  Dossier ID:    {_g(ctx, 'dossier_id')}\n"
        f"  Activity type: {_g(ctx, 'activity_type', 'submission_type', default='ANDS')}\n"
        f"  Sequence:      {_g(ctx, 'sequence', default='0000')}\n\n"
        "-- Product Information (PI) --\n"
        f"  Product name:  {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  DIN:           {_g(ctx, 'din')}\n\n"
        "Note: since Oct 1, 2020 the REP web template replaces the HC/SC 3011 "
        "form. Submit the generated CO/RT/PI XML with the transaction.\n")
    return _doc("Drug Submission Application Form (REP)", body,
                "rep-application-form.txt")


def patent_form_iv(ctx: dict) -> dict:
    body = (
        "Form IV — Patent List (Patented Medicines (Notice of Compliance) "
        "Regulations)\n\n"
        f"  Drug product:              {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Product:{_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:             {_g(ctx, 'crp_din')}\n\n"
        "Patents / Certificates of Supplementary Protection on the Patent "
        "Register for the reference product that this ANDS addresses:\n"
        f"  {_g(ctx, 'patents', default='[list each patent/CSP number and the address (I/II/III/IV) taken]')}\n\n"
        "The sponsor certifies the above list is complete and accurate.\n")
    return _doc("Patent List — Form IV", body, "patent-form-iv.txt")


def ands_attestation(ctx: dict) -> dict:
    body = (
        "The sponsor attests that the information and material contained in this "
        "Abbreviated New Drug Submission are accurate and complete, and are not "
        "false or misleading.\n\n"
        "The sponsor confirms:\n"
        "  [ ] The generic is pharmaceutically equivalent to the Canadian "
        "Reference Product (same medicinal ingredient(s), strength, dosage form,"
        " route).\n"
        "  [ ] The comparative bioavailability / bioequivalence evidence "
        "supports the claim.\n"
        "  [ ] The submission complies with the Food and Drugs Act and "
        "Regulations.\n\n"
        f"  Product:    {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Dossier ID: {_g(ctx, 'dossier_id')}\n\n"
        "  Authorized signer: ______________________   Date: ____________\n\n"
        "Note: the ANDS Sponsor Attestation Checklist is obtained from Health "
        "Canada by email (not the public forms page).\n")
    return _doc("ANDS Sponsor Attestation", body, "ands-attestation.txt")


def qos_ce_scaffold(ctx: dict) -> dict:
    body = (
        "Quality Overall Summary — Chemical Entities, Bioequivalence "
        "(QOS-CE(BE))\n\n"
        f"  Drug product: {_g(ctx, 'drug_product', 'product', 'title')}\n\n"
        "2.3.S  DRUG SUBSTANCE\n"
        "  2.3.S.1  General information\n"
        "  2.3.S.2  Manufacture\n"
        "  2.3.S.3  Characterisation\n"
        "  2.3.S.4  Control of drug substance\n"
        "  2.3.S.7  Stability\n\n"
        "2.3.P  DRUG PRODUCT\n"
        "  2.3.P.1  Description and composition\n"
        "  2.3.P.2  Pharmaceutical development\n"
        "  2.3.P.3  Manufacture\n"
        "  2.3.P.5  Control of drug product\n"
        "  2.3.P.7  Stability\n\n"
        "Complete each subsection summarising the Module 3 data. A .docx copy is "
        "expected alongside the PDF.\n")
    return _doc("Quality Overall Summary (QOS-CE(BE))", body, "qos-ce-be.txt")


def cs_be(ctx: dict) -> dict:
    body = (
        "Comprehensive Summary — Bioequivalence (CS-BE)\n\n"
        f"  Test product:            {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Prod: {_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:           {_g(ctx, 'crp_din')}\n"
        f"  Dosage form / strength:  {_g(ctx, 'dosage_form')} / {_g(ctx, 'strength')}\n\n"
        "Pivotal comparative bioavailability study\n"
        f"  Design:                  {_g(ctx, 'study_design', default='single-dose, fasting, crossover')}\n"
        f"  AUC 90% CI:              {_g(ctx, 'auc_ci', default='[__–__%] (limits 80.00–125.00%)')}\n"
        f"  Cmax 90% CI / PE:        {_g(ctx, 'cmax', default='[__–__%] / [__%]')}\n"
        f"  Ruleset:                 {_g(ctx, 'ruleset', default='ICH M13A / legacy per dosage-form class + filing date')}\n\n"
        "Conclusion: the test product is / is not bioequivalent to the reference "
        "product on the above parameters.\n")
    return _doc("Comprehensive Summary — Bioequivalence (CS-BE)", body,
                "cs-be.txt")


GENERATORS = {
    "cover_letter": cover_letter,
    "rep_application_form": rep_application_form,
    "patent_form_iv": patent_form_iv,
    "ands_attestation": ands_attestation,
    "qos_ce_scaffold": qos_ce_scaffold,
    "cs_be": cs_be,
}


def generate(generator_key: str, ctx: dict) -> dict:
    """Produce the document for a generator key. Raises KeyError if unknown."""
    fn = GENERATORS[_s(generator_key)]
    return fn(ctx or {})
