"""In-app document authoring — portal-generated eCTD documents (pure).

For the sections Health Canada lets the sponsor author from their own data, the
portal produces a structured draft (grounded in HC's templates) so the filer
doesn't start from a blank page. Prose documents are rendered to a real **PDF**
(via :mod:`pdfgen`) since every Module-1 leaf HC accepts must be PDF; the REP
application form is emitted as **XML** (the REP CO/RT/PI backbone). The service
stores these bytes through the same document store and files the same eCTD leaf as
an upload (``origin="generated"``). Drafts are clearly marked for review.

Keyed by the section tree's ``generator_key``.
"""

from __future__ import annotations

from . import pdfgen, pm_xml

_ACTIVITY_LABELS = {
    "ANDS": "Abbreviated New Drug Submission (ANDS)",
    "NDS": "New Drug Submission (NDS)",
    "SANDS": "Supplement to an ANDS (SANDS)",
    "SNDS": "Supplement to an NDS (SNDS)",
    "DIN": "Drug Identification Number Application (DINA)",
}
_DRAFT = ("[DRAFT generated by ANDS Studio - review and finalise before "
          "signing/filing.]\n\n")

# The base-14 PDF fonts encode Latin-1; map smart punctuation to ASCII so it
# doesn't render as '?' in the generated PDF.
_ASCII_MAP = {"—": "-", "–": "-", "‘": "'", "’": "'",
              "“": '"', "”": '"', "…": "...", "≤": "<=",
              "≥": ">=", "×": "x"}


def _ascii(s: str) -> str:
    for k, v in _ASCII_MAP.items():
        s = s.replace(k, v)
    return s


def _s(v) -> str:
    return str(v if v is not None else "").strip()


def _g(ctx: dict, *keys, default="—") -> str:
    for k in keys:
        v = _s((ctx or {}).get(k))
        if v:
            return v
    return default


def _pdf(title: str, body: str, filename_stem: str) -> dict:
    return {"title": title, "filename": f"{filename_stem}.pdf",
            "content_type": "application/pdf",
            "body": pdfgen.text_pdf(_ascii(title), _ascii(_DRAFT + body))}


def _xesc(v: str) -> str:
    return (_s(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def cover_letter(ctx: dict) -> dict:
    body = (
        # the sponsor is the SPONSOR (company), never the product/title —
        # falling through to 'title' printed the drug name as the sponsor.
        f"Sponsor:        {_g(ctx, 'sponsor', 'applicant', 'company')}\n"
        f"Company ID:     {_g(ctx, 'company_id')}\n"
        f"Dossier ID:     {_g(ctx, 'dossier_id')}\n"
        f"Drug product:   {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"Activity type:  {_ACTIVITY_LABELS.get(_g(ctx, 'activity_type', 'submission_type', default='ANDS').upper(), 'Abbreviated New Drug Submission (ANDS)')}\n"
        f"Sequence:       {_g(ctx, 'sequence', default='0000')}\n\n"
        "This cover letter accompanies the regulatory transaction identified "
        "above, submitted to Health Canada in eCTD format. The enclosed documents "
        "are organised per the Organization and document placement for Canadian "
        "Module 1 table.\n\n"
        "Regulatory contact: " + _g(ctx, 'contact', 'contact_email') + "\n")
    return _pdf("Health Canada — Cover Letter", body, "cover-letter")


def rep_application_form(ctx: dict) -> dict:
    """The REP Regulatory Transaction backbone (CO / RT / PI) as XML.

    The CRO rejected the earlier draft because the sponsor company fields fell
    through to the product title: the company id was empty and the PRODUCT name
    sat in the sponsor <name> slot. The three identities are now kept distinct:

    - COMPANY_ID / COMPANY_NAME come from the sponsor (``company_id`` and
      ``sponsor``/``applicant`` — NEVER the product ``title``);
    - PRODUCT_NAME comes from ``drug_product``/``product``/``title``;
    - DIN comes from ``din`` (empty until assigned by HC at NOC).

    ``status="draft"`` stays a document attribute only — never a required id.
    """
    # XML fields default to empty (never the '—' display sentinel).
    company_id = _xesc(_g(ctx, 'company_id', default=''))
    company_name = _xesc(_g(ctx, 'sponsor', 'applicant', 'company', default=''))
    dossier_id = _xesc(_g(ctx, 'dossier_id', default=''))
    dossier_type = _xesc(_g(ctx, 'dossier_type', 'submission_type',
                            'activity_type', default='ANDS'))
    activity = _xesc(_g(ctx, 'activity_type', 'submission_type', default='ANDS'))
    sequence = _xesc(_g(ctx, 'sequence', default='0000'))
    seq_desc = _xesc(_g(ctx, 'sequence_description', 'purpose',
                         default='Original submission'))
    product = _xesc(_g(ctx, 'drug_product', 'product', 'title', default=''))
    din = _xesc(_g(ctx, 'din', default=''))
    xml = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<REGULATORY_TRANSACTION generated-by=\"ands-studio\" status=\"draft\">\n"
        f"  <COMPANY_ID>{company_id}</COMPANY_ID>\n"
        f"  <COMPANY_NAME>{company_name}</COMPANY_NAME>\n"
        f"  <DOSSIER_ID>{dossier_id}</DOSSIER_ID>\n"
        f"  <DOSSIER_TYPE>{dossier_type}</DOSSIER_TYPE>\n"
        f"  <ACTIVITY_TYPE>{activity}</ACTIVITY_TYPE>\n"
        f"  <SEQUENCE_NUMBER>{sequence}</SEQUENCE_NUMBER>\n"
        f"  <SEQUENCE_DESCRIPTION>{seq_desc}</SEQUENCE_DESCRIPTION>\n"
        f"  <PRODUCT_NAME>{product}</PRODUCT_NAME>\n"
        f"  <DIN>{din}</DIN>\n"
        "</REGULATORY_TRANSACTION>\n")
    return {"title": "Drug Submission Application Form (REP)",
            "filename": "rep-application-form.xml",
            "content_type": "application/xml",
            "body": xml.encode("utf-8")}


def patent_form_v(ctx: dict) -> dict:
    """The generic's s.5 declaration (Form V) under the PM(NOC) Regulations.

    Form IV (Patent List) is the innovator's instrument; the generic FILES
    Form V declaring, per patent/CSP on the Patent Register for the Canadian
    Reference Product, ONE s.5 statement — and SERVES a Notice of Allegation
    (NOA) when it alleges invalidity or non-infringement.
    """
    patents = _g(ctx, 'patents', default="")
    if patents and patents != "—":
        declaration = (
            "Under section 5 of the Patented Medicines (Notice of "
            "Compliance)\n"
            "Regulations the sponsor declares, in respect of EACH patent/CSP "
            "on the\n"
            "Patent Register for the Canadian Reference Product, ONE of the\n"
            "following statements:\n"
            "  - not addressed: no claim within the scope of s.5(1) is "
            "engaged;\n"
            "  - accepts expiry: no NOC is sought before the patent/CSP "
            "expires;\n"
            "  - alleges invalidity: the patent/CSP is invalid or void;\n"
            "  - alleges non-infringement: no claim of the patent/CSP would "
            "be infringed.\n\n"
            f"  Patent/CSP number(s): {patents}\n"
            f"  Expiry:               {_g(ctx, 'patent_expiry', default='[expiry date per patent]')}\n"
            f"  s.5 statement:        {_g(ctx, 'allegation', default='[one per patent: not addressed / accepts expiry / alleges invalidity / alleges non-infringement]')}\n\n"
            "Where the statement alleges invalidity or non-infringement, "
            "the sponsor\n"
            "serves a Notice of Allegation (NOA) on the innovator under "
            "s.5(3).\n")
    else:
        declaration = (
            "The Patent Register contains no patents/CSPs for the Canadian\n"
            "Reference Product relevant to this submission; no s.5 statement\n"
            "is required and no Notice of Allegation need be served.\n")
    body = (
        f"  Drug product:               {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Product: {_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:              {_g(ctx, 'crp_din')}\n\n"
        + declaration +
        "\nThe sponsor declares the above is complete and accurate.\n")
    return _pdf("Form V — Declaration Re: Patent List (PM(NOC) Regulations)",
                body, "form-v-declaration")


def ands_attestation(ctx: dict) -> dict:
    body = (
        "The sponsor attests that the information and material in this Abbreviated "
        "New Drug Submission are accurate and complete, and are not false or "
        "misleading.\n\n"
        "The sponsor confirms:\n"
        "  [ ] The generic is pharmaceutically equivalent to the Canadian "
        "Reference Product (same medicinal ingredient(s), strength, dosage form, "
        "route).\n"
        "  [ ] The comparative bioavailability / bioequivalence evidence supports "
        "the claim.\n"
        "  [ ] The submission complies with the Food and Drugs Act and "
        "Regulations.\n\n"
        f"  Product:    {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Dossier ID: {_g(ctx, 'dossier_id')}\n\n"
        "  Authorized signer: ______________________   Date: ____________\n\n"
        "Note: the ANDS Sponsor Attestation Checklist is obtained from Health "
        "Canada by email (not the public forms page).\n")
    return _pdf("ANDS Sponsor Attestation", body, "ands-attestation")


def qos_ce_scaffold(ctx: dict) -> dict:
    body = (
        f"  Drug product: {_g(ctx, 'drug_product', 'product', 'title')}\n\n"
        "2.3.S  DRUG SUBSTANCE\n"
        "  2.3.S.1  General information\n"
        "  2.3.S.2  Manufacture\n"
        "  2.3.S.3  Characterisation\n"
        "  2.3.S.4  Control of drug substance\n"
        "  2.3.S.5  Reference standards or materials\n"
        "  2.3.S.6  Container closure system\n"
        "  2.3.S.7  Stability\n\n"
        "2.3.P  DRUG PRODUCT\n"
        "  2.3.P.1  Description and composition\n"
        "  2.3.P.2  Pharmaceutical development\n"
        "  2.3.P.3  Manufacture\n"
        "  2.3.P.4  Control of excipients\n"
        "  2.3.P.5  Control of drug product\n"
        "  2.3.P.6  Reference standards or materials\n"
        "  2.3.P.7  Container closure system\n"
        "  2.3.P.8  Stability\n\n"
        "Complete each subsection summarising the Module 3 data. A .docx copy is "
        "expected alongside the PDF.\n")
    return _pdf("Quality Overall Summary (QOS-CE(BE))", body, "qos-ce-be")


def cs_be(ctx: dict) -> dict:
    body = (
        f"  Test product:             {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Prod:  {_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:            {_g(ctx, 'crp_din')}\n"
        f"  Dosage form / strength:   {_g(ctx, 'dosage_form')} / {_g(ctx, 'strength')}\n\n"
        "Pivotal comparative bioavailability study\n"
        f"  Design:                   {_g(ctx, 'study_design', default='single-dose, fasting, crossover')}\n"
        f"  AUC 90% CI:               {_g(ctx, 'auc_ci', default='[__-__%] (limits 80.00-125.00%)')}\n"
        f"  Cmax 90% CI / PE:         {_g(ctx, 'cmax', default='[__-__%] / [__%]')}\n"
        f"  Ruleset:                  {_g(ctx, 'ruleset', default='ICH M13A / legacy per dosage-form class + filing date')}\n\n"
        "Conclusion: the test product is / is not bioequivalent to the reference "
        "product on the above parameters.\n")
    return _pdf("Comprehensive Summary — Bioequivalence (CS-BE)", body, "cs-be")


def _field_value(field: dict, form: dict) -> str:
    """The filled value for one schema field, or a clear placeholder."""
    v = _s((form or {}).get(field.get("name")))
    if v:
        return v
    if field.get("required"):
        return f"[PLACEHOLDER: {field.get('label') or field.get('name')}]"
    return "(not provided)"


def structured_document(schema: dict, form: dict, ctx: dict | None = None) -> dict:
    """Universal generator: render a section's filled form schema into a clean,
    well-headed PDF/A-1b-clean PDF (via :mod:`pdfgen`).

    Each field is laid out as ``Label: value`` (prose fields get their own
    block), bilingual fields are flagged, and required-but-empty fields render
    an explicit ``[PLACEHOLDER: …]`` rather than silently blank — honest about
    what the filer still owes. The document carries the ``_DRAFT`` watermark;
    nothing here is claimed HC-accepted.
    """
    schema = schema or {}
    form = form or {}
    title = _s(schema.get("title")) or "eCTD Document"
    section = _s(schema.get("section"))
    lines: list[str] = []
    desc = _s(schema.get("description"))
    if desc:
        lines.append(desc)
        lines.append("")
    if section:
        lines.append(f"eCTD section: {section}")
        lines.append("")
    for field in schema.get("fields", []):
        label = _s(field.get("label") or field.get("name"))
        if field.get("bilingual"):
            label += " (bilingual: EN + FR)"
        value = _field_value(field, form)
        if field.get("prose") or field.get("type") == "textarea":
            lines.append(f"{label}:")
            for para in value.split("\n"):
                lines.append(f"  {para}")
            lines.append("")
        else:
            lines.append(f"{label}: {value}")
    body = "\n".join(lines).rstrip() + "\n"
    stem = f"section-{section.replace('.', '-').lower()}" if section else "document"
    return _pdf(title, body, stem)


# --- Product Monograph 1.3.1 — the bilingual XML PM builder -----------------

# Map each PM form field onto a pm_xml controlled-vocabulary section code and a
# human title. The clinical narratives + PMI parts become <section> elements;
# proper/brand name + DIN drive the XML PM's required identity elements. The
# tuple order is the order sections appear in the built XML. Each entry is
# (form_field, section_code, EN section title). ``patient-information`` is a
# single rolled-up Part III section (its four PMI parts are concatenated).
_PM_SECTION_MAP = (
    ("indications", "indications", "Indications and Clinical Use"),
    ("contraindications", "contraindications", "Contraindications"),
    ("serious_warnings", "warnings", "Serious Warnings and Precautions"),
    ("dosage_administration", "dosage", "Dosage and Administration"),
    ("adverse_reactions", "adverse-reactions", "Adverse Reactions"),
    ("drug_interactions", "warnings", "Drug Interactions"),
    ("action_clinical_pharmacology", "pharmacology",
     "Action and Clinical Pharmacology"),
    ("storage_stability", "storage", "Storage and Stability"),
    ("dosage_forms_composition", "supply",
     "Dosage Forms, Composition and Packaging"),
)
# Part III PMI parts (rolled into the single ``patient-information`` section).
_PM_PMI_PARTS = (
    ("pmi_what_it_is_for", "What it is used for"),
    ("pmi_how_to_take", "How to take it"),
    ("pmi_warnings", "Warnings and precautions"),
    ("pmi_side_effects", "Possible side effects"),
)


def _pm_bilingual_text(form: dict, field: str) -> str:
    """The EN value of a PM field, with its ``<field>_fr`` French value
    appended (labelled) when present — HC PM sections are bilingual."""
    en = _s((form or {}).get(field))
    fr = _s((form or {}).get(f"{field}_fr"))
    if en and fr:
        return f"[EN] {en}\n[FR] {fr}"
    return en or fr


def _pm_data_from_form(form: dict, lang: str) -> dict:
    """Map a filled PM form onto :func:`pm_xml.build_monograph_xml` input.

    ``product_name`` is the brand name (falling back to the proper name); the
    clinical narratives become controlled-vocabulary <section>s and the four
    Part III PMI parts roll up into one ``patient-information`` section. Blank
    fields are dropped (they would only render as '—' placeholders)."""
    form = form or {}
    product_name = _s(form.get("brand_name")) or _s(form.get("proper_name")) \
        or _s(form.get("drug_product"))
    sections = []
    for field, code, title in _PM_SECTION_MAP:
        text = _pm_bilingual_text(form, field)
        if text:
            sections.append({"code": code, "title": title, "text": text})
    pmi_blocks = []
    for field, label in _PM_PMI_PARTS:
        text = _pm_bilingual_text(form, field)
        if text:
            pmi_blocks.append(f"{label}:\n{text}")
    if pmi_blocks:
        sections.append({"code": "patient-information",
                         "title": "Patient Medication Information (Part III)",
                         "text": "\n\n".join(pmi_blocks)})
    return {"lang": _s(lang).lower() or "en",
            "product_name": product_name,
            "din": _s(form.get("din")),
            "sections": sections}


def _pm_pdf_body(form: dict, pm_data: dict) -> str:
    """A readable text rendering of the PM for the PDF artifact."""
    form = form or {}
    lines = [
        f"Proper name:               {_g(form, 'proper_name')}",
        f"Brand name:                {_g(form, 'brand_name')}",
        f"DIN:                       {_g(form, 'din')}",
        f"Therapeutic classification:{' '}"
        f"{_g(form, 'therapeutic_classification')}",
        "",
        "PART I — HEALTH PROFESSIONAL INFORMATION",
        "",
    ]
    for sec in pm_data["sections"]:
        if sec["code"] == "patient-information":
            continue
        lines.append(sec["title"] + ":")
        for para in sec["text"].split("\n"):
            lines.append(f"  {para}")
        lines.append("")
    lines.append("PART III — PATIENT MEDICATION INFORMATION")
    lines.append("")
    pmi = next((s for s in pm_data["sections"]
                if s["code"] == "patient-information"), None)
    if pmi:
        for para in pmi["text"].split("\n"):
            lines.append(f"  {para}")
    else:
        lines.append("  (not provided)")
    return "\n".join(lines).rstrip() + "\n"


def product_monograph(ctx: dict) -> dict:
    """Author 1.3.1 from a filled bilingual PM form: build a VALIDATED XML PM
    (:func:`pm_xml.build_monograph_xml`) AND a readable PDF rendering.

    The top-level dict is the XML PM (the machine-readable artifact HC's XML PM
    mandate targets); a ``artifacts`` list carries BOTH the XML (with its
    validation result) and the PDF so the caller can persist each. Honest: the
    PDF carries the ``_DRAFT`` watermark and the XML is only ever a draft the
    filer reviews — nothing here is claimed HC-accepted."""
    ctx = ctx or {}
    form = ctx.get("form")
    if not isinstance(form, dict):
        form = ctx
    lang = _s(ctx.get("lang")) or _s(form.get("lang")) or "en"
    pm_data = _pm_data_from_form(form, lang)
    xml = pm_xml.build_monograph_xml(pm_data)
    validation = pm_xml.validate_monograph_xml(xml)
    product = pm_data["product_name"] or "Product Monograph"
    xml_artifact = {
        "title": f"Product Monograph — XML ({product})",
        "filename": f"product-monograph-{lang}.xml",
        "content_type": "application/xml",
        "body": xml.encode("utf-8"),
        "validation": validation,
    }
    pdf = _pdf("Product Monograph (bilingual, incl. PMI)",
               _pm_pdf_body(form, pm_data), f"product-monograph-{lang}")
    pdf_artifact = {**pdf, "validation": None}
    # primary = the XML PM; both artifacts travel in ``artifacts``.
    return {**xml_artifact, "artifacts": [xml_artifact, pdf_artifact]}


GENERATORS = {
    "cover_letter": cover_letter,
    "rep_application_form": rep_application_form,
    "patent_form_v": patent_form_v,
    # Legacy alias: section states stored before the Form IV -> Form V
    # correction keep resolving (the section tree now emits patent_form_v).
    "patent_form_iv": patent_form_v,
    "ands_attestation": ands_attestation,
    "qos_ce_scaffold": qos_ce_scaffold,
    "cs_be": cs_be,
    "pm_xml": product_monograph,
}

# Prose-PDF documents the interactive (LLM chat) drafting flow can author.
# The REP form is structured XML — free-text drafting would corrupt it, so it
# stays deterministic-only. Values are the (title, filename stem) for the PDF
# built from a finalised chat draft.
_FORM_V = ("Form V — Declaration Re: Patent List (PM(NOC) Regulations)",
           "form-v-declaration")
LLM_DRAFTABLE = {
    "cover_letter": ("Health Canada — Cover Letter", "cover-letter"),
    "patent_form_v": _FORM_V,
    "patent_form_iv": _FORM_V,        # legacy alias (stored section states)
    "ands_attestation": ("ANDS Sponsor Attestation", "ands-attestation"),
    "qos_ce_scaffold": ("Quality Overall Summary (QOS-CE(BE))", "qos-ce-be"),
    "cs_be": ("Comprehensive Summary — Bioequivalence (CS-BE)", "cs-be"),
}


def generate(generator_key: str, ctx: dict) -> dict:
    """Produce the document for a generator key. Raises KeyError if unknown.

    A finalised interactive (LLM chat) draft in ``ctx['llm_draft']`` takes
    priority over the deterministic template for LLM-draftable documents.

    The universal ``"structured"`` key renders a section's filled form schema:
    the section is taken from ``ctx['section']`` and the filled field map from
    ``ctx['form']`` (falling back to ``ctx`` itself). Its schema is looked up
    via :mod:`form_schemas`."""
    key = _s(generator_key)
    ctx = ctx or {}
    if key == "structured":
        # lazy import — form_schemas is a leaf, but keep generators import-light
        from . import form_schemas
        section = _s(ctx.get("section"))
        schema = form_schemas.form_schema(section)
        if not schema:
            raise KeyError(f"no form schema for section {section!r}")
        form = ctx.get("form")
        if not isinstance(form, dict):
            form = ctx
        return structured_document(schema, form, ctx)
    fn = GENERATORS[key]
    llm_draft = _s(ctx.get("llm_draft"))
    if llm_draft and key in LLM_DRAFTABLE:
        title, stem = LLM_DRAFTABLE[key]
        return _pdf(title, llm_draft, stem)
    return fn(ctx)
