"""In-app document authoring — portal-generated eCTD documents (pure).

For the sections Health Canada lets the sponsor author from their own data, the
portal produces a structured draft (grounded in HC's templates) so the filer
doesn't start from a blank page. Prose documents are rendered to a real **PDF**
(via :mod:`pdfgen`) since every Module-1 leaf HC accepts must be PDF; the REP
application form is emitted as **XML** (the REP CO/RT/PI backbone). The service
stores these bytes through the same document store and files the same eCTD leaf as
an upload (``origin="generated"``). Drafts are clearly marked for review.

Keyed by the section tree's ``generator_key``.
"""

from __future__ import annotations

from . import pdfgen

_ACTIVITY_LABELS = {
    "ANDS": "Abbreviated New Drug Submission (ANDS)",
    "NDS": "New Drug Submission (NDS)",
    "SANDS": "Supplement to an ANDS (SANDS)",
    "SNDS": "Supplement to an NDS (SNDS)",
    "DIN": "Drug Identification Number Application (DINA)",
}
_DRAFT = ("[DRAFT generated by ANDS Studio - review and finalise before "
          "signing/filing.]\n\n")

# The base-14 PDF fonts encode Latin-1; map smart punctuation to ASCII so it
# doesn't render as '?' in the generated PDF.
_ASCII_MAP = {"—": "-", "–": "-", "‘": "'", "’": "'",
              "“": '"', "”": '"', "…": "...", "≤": "<=",
              "≥": ">=", "×": "x"}


def _ascii(s: str) -> str:
    for k, v in _ASCII_MAP.items():
        s = s.replace(k, v)
    return s


def _s(v) -> str:
    return str(v if v is not None else "").strip()


def _g(ctx: dict, *keys, default="—") -> str:
    for k in keys:
        v = _s((ctx or {}).get(k))
        if v:
            return v
    return default


def _pdf(title: str, body: str, filename_stem: str) -> dict:
    return {"title": title, "filename": f"{filename_stem}.pdf",
            "content_type": "application/pdf",
            "body": pdfgen.text_pdf(_ascii(title), _ascii(_DRAFT + body))}


def _xesc(v: str) -> str:
    return (_s(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def cover_letter(ctx: dict) -> dict:
    body = (
        f"Sponsor:        {_g(ctx, 'applicant', 'company', 'title')}\n"
        f"Company ID:     {_g(ctx, 'company_id')}\n"
        f"Dossier ID:     {_g(ctx, 'dossier_id')}\n"
        f"Drug product:   {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"Activity type:  {_ACTIVITY_LABELS.get(_g(ctx, 'activity_type', 'submission_type', default='ANDS').upper(), 'Abbreviated New Drug Submission (ANDS)')}\n"
        f"Sequence:       {_g(ctx, 'sequence', default='0000')}\n\n"
        "This cover letter accompanies the regulatory transaction identified "
        "above, submitted to Health Canada in eCTD format. The enclosed documents "
        "are organised per the Organization and document placement for Canadian "
        "Module 1 table.\n\n"
        "Regulatory contact: " + _g(ctx, 'contact', 'contact_email') + "\n")
    return _pdf("Health Canada — Cover Letter", body, "cover-letter")


def rep_application_form(ctx: dict) -> dict:
    """The REP CO/RT/PI backbone as XML (replaces the old HC/SC 3011)."""
    # XML fields default to empty (never the '—' display sentinel).
    company = _xesc(_g(ctx, 'applicant', 'company', 'title', default=''))
    company_id = _xesc(_g(ctx, 'company_id', default=''))
    dossier_id = _xesc(_g(ctx, 'dossier_id', default=''))
    activity = _xesc(_g(ctx, 'activity_type', 'submission_type', default='ANDS'))
    sequence = _xesc(_g(ctx, 'sequence', default='0000'))
    product = _xesc(_g(ctx, 'drug_product', 'product', 'title', default=''))
    din = _xesc(_g(ctx, 'din', default=''))
    xml = (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<rep-application generated-by=\"ands-studio\" status=\"draft\">\n"
        f"  <company id=\"{company_id}\"><name>{company}</name></company>\n"
        "  <regulatory-transaction>\n"
        f"    <dossier-id>{dossier_id}</dossier-id>\n"
        f"    <activity-type>{activity}</activity-type>\n"
        f"    <sequence>{sequence}</sequence>\n"
        "  </regulatory-transaction>\n"
        "  <product-information>\n"
        f"    <product-name>{product}</product-name>\n"
        f"    <din>{din}</din>\n"
        "  </product-information>\n"
        "</rep-application>\n")
    return {"title": "Drug Submission Application Form (REP)",
            "filename": "rep-application-form.xml",
            "content_type": "application/xml",
            "body": xml.encode("utf-8")}


def patent_form_iv(ctx: dict) -> dict:
    patents = _g(ctx, 'patents', default="")
    if patents and patents != "—":
        register = (
            "Patents / Certificates of Supplementary Protection on the Patent "
            "Register for the reference product that this ANDS addresses:\n"
            f"  Patent/CSP number(s): {patents}\n"
            f"  Expiry:               {_g(ctx, 'patent_expiry', default='[expiry date per patent]')}\n"
            f"  Allegation (s.5):     {_g(ctx, 'allegation', default='[per patent: not infringed / invalid / accept expiry / no claim]')}\n")
    else:
        register = ("The Patent Register contains no patents/CSPs for the "
                    "Canadian Reference Product relevant to this submission "
                    "(no s.5 allegation is required).\n")
    body = (
        f"  Drug product:               {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Product: {_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:              {_g(ctx, 'crp_din')}\n\n"
        + register +
        "\nUnder the Patented Medicines (Notice of Compliance) Regulations the "
        "sponsor certifies the above is complete and accurate.\n")
    return _pdf("Patent List — Form IV", body, "patent-form-iv")


def ands_attestation(ctx: dict) -> dict:
    body = (
        "The sponsor attests that the information and material in this Abbreviated "
        "New Drug Submission are accurate and complete, and are not false or "
        "misleading.\n\n"
        "The sponsor confirms:\n"
        "  [ ] The generic is pharmaceutically equivalent to the Canadian "
        "Reference Product (same medicinal ingredient(s), strength, dosage form, "
        "route).\n"
        "  [ ] The comparative bioavailability / bioequivalence evidence supports "
        "the claim.\n"
        "  [ ] The submission complies with the Food and Drugs Act and "
        "Regulations.\n\n"
        f"  Product:    {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Dossier ID: {_g(ctx, 'dossier_id')}\n\n"
        "  Authorized signer: ______________________   Date: ____________\n\n"
        "Note: the ANDS Sponsor Attestation Checklist is obtained from Health "
        "Canada by email (not the public forms page).\n")
    return _pdf("ANDS Sponsor Attestation", body, "ands-attestation")


def qos_ce_scaffold(ctx: dict) -> dict:
    body = (
        f"  Drug product: {_g(ctx, 'drug_product', 'product', 'title')}\n\n"
        "2.3.S  DRUG SUBSTANCE\n"
        "  2.3.S.1  General information\n"
        "  2.3.S.2  Manufacture\n"
        "  2.3.S.3  Characterisation\n"
        "  2.3.S.4  Control of drug substance\n"
        "  2.3.S.5  Reference standards or materials\n"
        "  2.3.S.6  Container closure system\n"
        "  2.3.S.7  Stability\n\n"
        "2.3.P  DRUG PRODUCT\n"
        "  2.3.P.1  Description and composition\n"
        "  2.3.P.2  Pharmaceutical development\n"
        "  2.3.P.3  Manufacture\n"
        "  2.3.P.4  Control of excipients\n"
        "  2.3.P.5  Control of drug product\n"
        "  2.3.P.6  Reference standards or materials\n"
        "  2.3.P.7  Container closure system\n"
        "  2.3.P.8  Stability\n\n"
        "Complete each subsection summarising the Module 3 data. A .docx copy is "
        "expected alongside the PDF.\n")
    return _pdf("Quality Overall Summary (QOS-CE(BE))", body, "qos-ce-be")


def cs_be(ctx: dict) -> dict:
    body = (
        f"  Test product:             {_g(ctx, 'drug_product', 'product', 'title')}\n"
        f"  Canadian Reference Prod:  {_g(ctx, 'crp_brand', 'reference_product')}\n"
        f"  Reference DIN:            {_g(ctx, 'crp_din')}\n"
        f"  Dosage form / strength:   {_g(ctx, 'dosage_form')} / {_g(ctx, 'strength')}\n\n"
        "Pivotal comparative bioavailability study\n"
        f"  Design:                   {_g(ctx, 'study_design', default='single-dose, fasting, crossover')}\n"
        f"  AUC 90% CI:               {_g(ctx, 'auc_ci', default='[__-__%] (limits 80.00-125.00%)')}\n"
        f"  Cmax 90% CI / PE:         {_g(ctx, 'cmax', default='[__-__%] / [__%]')}\n"
        f"  Ruleset:                  {_g(ctx, 'ruleset', default='ICH M13A / legacy per dosage-form class + filing date')}\n\n"
        "Conclusion: the test product is / is not bioequivalent to the reference "
        "product on the above parameters.\n")
    return _pdf("Comprehensive Summary — Bioequivalence (CS-BE)", body, "cs-be")


GENERATORS = {
    "cover_letter": cover_letter,
    "rep_application_form": rep_application_form,
    "patent_form_iv": patent_form_iv,
    "ands_attestation": ands_attestation,
    "qos_ce_scaffold": qos_ce_scaffold,
    "cs_be": cs_be,
}


def generate(generator_key: str, ctx: dict) -> dict:
    """Produce the document for a generator key. Raises KeyError if unknown."""
    fn = GENERATORS[_s(generator_key)]
    return fn(ctx or {})
