"""Repository port for the dossier service (hexagonal)."""

from __future__ import annotations

from typing import Protocol


class DossierRepository(Protocol):
    # content plans (REQ-103)
    def create_plan(self, dossier_id: str, submission_type: str,
                    items: list) -> dict: ...
    def get_plan(self, plan_id: str) -> dict | None: ...
    def get_plan_by_dossier(self, dossier_id: str) -> dict | None: ...
    def get_item(self, item_id: str) -> dict | None: ...
    def update_item(self, item_id: str, fields: dict) -> dict | None: ...

    # bilingual product monograph (REQ-098)
    def upsert_pm_leaf(self, leaf: dict) -> dict: ...
    def list_pm_leaves(self, dossier_id: str) -> list[dict]: ...

    # eCTD assembly model (REQ-107)
    def get_dossier(self, dossier_id: str) -> dict | None: ...
    def save_dossier(self, model: dict) -> dict: ...

    # submission archive / binder (REQ-110)
    def save_binder(self, dossier_id: str, sequence: str, binder: dict) -> dict: ...
    def get_binder(self, binder_id: str) -> dict | None: ...
    def list_binders(self, dossier_id: str) -> list[dict]: ...
    def set_share_token(self, binder_id: str, token: str) -> None: ...
    def get_by_share_token(self, token: str) -> dict | None: ...
