"""Repository port for the dossier service (hexagonal)."""

from __future__ import annotations

from typing import Protocol


class DossierRepository(Protocol):
    # content plans (REQ-103)
    def create_plan(self, dossier_id: str, submission_type: str,
                    items: list) -> dict: ...
    def get_plan(self, plan_id: str) -> dict | None: ...
    def get_plan_by_dossier(self, dossier_id: str) -> dict | None: ...
    def get_item(self, item_id: str) -> dict | None: ...
    def update_item(self, item_id: str, fields: dict) -> dict | None: ...

    # bilingual product monograph (REQ-098)
    def upsert_pm_leaf(self, leaf: dict) -> dict: ...
    def list_pm_leaves(self, dossier_id: str) -> list[dict]: ...

    # eCTD assembly model (REQ-107)
    def get_dossier(self, dossier_id: str) -> dict | None: ...
    def save_dossier(self, model: dict) -> dict: ...

    # submission archive / binder (REQ-110)
    def save_binder(self, dossier_id: str, sequence: str, binder: dict) -> dict: ...
    def get_binder(self, binder_id: str) -> dict | None: ...
    def list_binders(self, dossier_id: str) -> list[dict]: ...
    def set_share_token(self, binder_id: str, token: str) -> None: ...
    def get_by_share_token(self, token: str) -> dict | None: ...

    # documents (byte-store backing)
    def put_document(self, rec: dict) -> dict: ...
    def get_document(self, doc_id: str) -> dict | None: ...
    def get_document_meta(self, doc_id: str) -> dict | None: ...
    def delete_document(self, doc_id: str) -> None: ...

    # per-section state
    def get_section_state(self, dossier_id: str, section: str) -> dict | None: ...
    def upsert_section_state(self, dossier_id: str, section: str,
                             entry: dict) -> dict: ...
    def list_section_state(self, dossier_id: str) -> dict: ...

    # dossier index (home catalog)
    def create_dossier_index(self, rec: dict) -> dict: ...
    def set_fee_status(self, dossier_id: str, fee_paid: bool,
                       sme_granted: bool) -> dict | None: ...
    def set_active_sequence(self, dossier_id: str, sequence: str) -> None: ...
    def get_dossier_index(self, dossier_id: str) -> dict | None: ...
    def list_dossier_index(self, tenant_id: str | None = None) -> list[dict]: ...
    def delete_dossier(self, dossier_id: str) -> bool: ...
    # WS3 recoverable delete: soft-archive + restore + trash view
    def list_archived_index(self, tenant_id: str | None = None) -> list[dict]: ...
    def archive_dossier(self, dossier_id: str, *, actor: str = "",
                        reason: str = "") -> bool: ...
    def restore_dossier(self, dossier_id: str) -> bool: ...

    # ADOPT-EVALIDATOR: user-attested external eValidator result (set/get the
    # latest attestation recorded against a dossier).
    def set_evalidator_attestation(self, dossier_id: str,
                                   attestation: dict) -> dict: ...
    def get_evalidator_attestation(self, dossier_id: str) -> dict | None: ...
    def set_attestation_with_event(self, dossier_id: str, attestation: dict, *,
                                   actor: str, event_type: str, tenant_id: str,
                                   data: dict) -> dict: ...

    # ADOPT-PART11-ESIGN: current signed e-signature manifest (set/get) + the
    # atomic persist-and-record-durable-event pairing.
    def set_esign_manifest(self, dossier_id: str, manifest: dict) -> dict: ...
    def get_esign_manifest(self, dossier_id: str) -> dict | None: ...
    def set_esign_with_event(self, dossier_id: str, manifest: dict, *,
                             actor: str, event_type: str, tenant_id: str,
                             data: dict) -> dict: ...

    # WS3 DURABLE Part-11 audit ledger — synchronous, same-DB, append-only.
    # The authoritative record of destructive rename/archive/restore; the
    # governance forward is a SECONDARY sink that may silently fail.
    def append_event(self, event_type: str, dossier_id: str, *,
                     actor: str = "", reason: str = "", tenant_id: str = "",
                     data: dict | None = None) -> dict: ...
    def list_events(self, dossier_id: str) -> list[dict]: ...
    def record_rename_chain(self, old_id: str, new_id: str) -> None: ...

    # WS3 ATOMIC mutation+ledger: pair the state change with its durable audit
    # write in one transaction (both commit or neither). Return the appended
    # event, or None when the mutation was a no-op (nothing committed).
    def archive_with_event(self, dossier_id: str, *, actor: str, reason: str,
                           event_type: str, tenant_id: str,
                           data: dict) -> dict | None: ...
    def restore_with_event(self, dossier_id: str, *, actor: str, reason: str,
                           event_type: str, tenant_id: str,
                           data: dict) -> dict | None: ...
    def rename_with_event(self, old_id: str, new_id: str, *, actor: str,
                          reason: str, event_type: str, tenant_id: str,
                          data: dict) -> dict | None: ...
